# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='testing',
        ),
    ]
